version: '3'

services:
  server:
    image: pclub/student-search
    ports:
      - "8080"
    environment:
      DB_LOC: /var/db/sqlite/students.db
    volumes:
      - ./database:/var/db/sqlite

  frontend:
    image: pclub/student-search:frontend
    ports:
      - "80"

volumes:
  data:
